#!/usr/bin/zsh

#### AUTOSTART ####
setxkbmap -option caps:ctrl_modifier
xmodmap -e "keycode 164 = Caps_Lock"

pkill sxhkd ; sxhkd &
pkill unclutter ; unclutter &
~/.config/polybar/launch.sh &
feh --bg-fill --randomize ~/Pictures/wallpaper/vienna/day/angels.jpg
/home/pirog/.config/scripts/battery/battery-low-alert.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# my custom
bspc config border_width           2
bspc config window_gap             0
# bspc config normal_border_color    "#D2D2CF"
bspc config focused_border_color   "#89d"
bspc config presel-feedback_color  "#a787e8"

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  false


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

